/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

public class App {
    /**
     * say Welcome.
     * @return - String */
    public String getGreeting() {
        return "Welcome to the Brain Games!";
    }

    public static void main(String[] args) {
        System.out.println(Cli.getGreeting());
    }
}
