name: Gradle build
on: push
jobs:
        gradle:
                runs-on: ubuntu-latest
                steps:
                - name: Checkout 
                  uses: actions/checkout@v2
               
                - name: Setup Gradle
                  uses: gradle/gradle-build-action@v2
    
                - name: Execute Gradle build
                  run: ./gradlew build
